### ISSUE TITLE
Rename repo to match recommend naming convention

### ISSUE THREAD

**Issue by simondeziel** [canonical/operator-template#16]
https://juju.is/docs/sdk/naming#heading--naming-repositories says:
> Add a suffix to it: -operator (because: Charmed Operator SDK)
> Prefer suffix over prefix

So `template-operator` would be a better name for the repo. The `README.md` and other files would need to be updated accordingly too.

**Comment by jnsgruk** [comment]
Interesting thought - any objections to renaming @simskij or @DomFleischmann?

**Comment by simskij** [comment]
not at all. in that case, it should probably even be `template-k8s-operator` as it currently defaults to Kubernetes.

**Comment by jnsgruk** [comment]
See, this is what I was afraid of ;-)

**Comment by DomFleischmann** [comment]
We are already calling it `template-operator` in the [metadata.yaml](https://github.com/canonical/operator-template/blob/ff9681614d56c31bdc7b146e8880b2c9266b1cb7/metadata.yaml#L6) we might as well be consistent.

**Comment by jnsgruk** [comment]
Yeh, I think that just `template-operator` is a better call. I'll do that now.
